server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    keyId: LTAI5tHAxJ86EMUFzfwAgm29
    keySecret: xzUrYpwMfYiyedxZBBDDimBUu5W0vu
    bucketName: srb-file-yuqi