server:
  port: 8120 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-sms # 服务名

  #spring:
  redis:
    host: 192.168.76.133
    port: 6379
    database: 0
    password: dc3 #默认为空
    timeout: 3000ms #最大等待时间，超时则抛出异常，否则请求一直等待
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0

#腾讯云短信
tencent:
  sms:
    secretId: AKIDfAydBUYOzL7mCMGuJTO3XpvmOltmQoxt
    secretKey: oNhmbIsHSO5ZrzvfEaljTzHJ7h8KH1Xo
    smsSdkAppId: 1400721392
    templateId: 1508428
    signName: 猪猪的技术日记公众号

feign:
  client:
    config:
      default:
        connectTimeout: 10000 #连接超时配置
        readTimeout: 600000 #执行超时配置
  sentinel:
    enabled: true

logging:
  level:
    com.atguigu.srb.sms.client.CoreUserInfoClient: DEBUG #以什么级别监控哪个接口